//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace School.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SchoolDatabaseEntities : DbContext
    {
        public SchoolDatabaseEntities()
            : base("name=SchoolDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Fee> Fees { get; set; }
        public virtual DbSet<GoverningBody> GoverningBodies { get; set; }
        public virtual DbSet<News> News { get; set; }
        public virtual DbSet<StudentRegistration> StudentRegistrations { get; set; }
        public virtual DbSet<TeacherRegistration> TeacherRegistrations { get; set; }
    }
}
