//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace School.Models
{
  using System;
  using System.Collections.Generic;
  using System.ComponentModel.DataAnnotations;
  public partial class StudentRegistration
  {

    public int Id { get; set; }

    [Required]
    [StringLength(50)]
    public string Name { get; set; }

    [Required]
    [StringLength(50)]
    [Display(Name = "Fathers Name")]
    public string FathersName { get; set; }

    [Required]
    [StringLength(50)]
    [Display(Name = "Mothers Name")]
    public string MothersName { get; set; }

    [Required]
    [StringLength(80)]
    [Display(Name = "Present Address")]
    public string PresentAddress { get; set; }

    [Required]
    [StringLength(150)]
    [Display(Name = "Permanenet Address")]
    public string ParmanentAddress { get; set; }

    [Required]
    public System.DateTime EnrollMentDate { get; set; }

    [Required]
    public string Class { get; set; }

    [Required]
    [StringLength(150)]
    public string Religion { get; set; }
  }
}
