//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace School.Models
{
  using System;
  using System.Collections.Generic;
  using System.ComponentModel.DataAnnotations;

  public partial class TeacherRegistration
  {
    public int Id { get; set; }

    [Required]
    [StringLength(50)]
    [Display(Name = "Teachers Name")]
    public string TeacherName { get; set; }

    [Required]
    [Display(Name = "Joining Date")]
    public System.DateTime JoiningDate { get; set; }

    [Required]
    [StringLength(50)]
    public string Graduation { get; set; }

    [Required]
    [StringLength(50)]

    public string Subject { get; set; }
  }
}
